/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/players/{username}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Player
         * @description Fetch new games from chess.com, store and classify them.
         */
        post: operations["sync_player_api_players__username__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/openings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Openings
         * @description Per-opening record over classified games, most-played first.
         *
         *     `since`/`until` (epoch seconds) restrict to a time window;
         *     `time_class` restricts to one time control.
         */
        get: operations["player_openings_api_players__username__openings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Games */
        get: operations["player_games_api_players__username__games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game Detail */
        get: operations["game_detail_api_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Player
         * @description Queue engine analysis; follow progress via the SSE endpoint.
         */
        post: operations["analyze_player_api_players__username__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/analyze/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analyze Progress
         * @description SSE stream for the player's current analysis run.
         */
        get: operations["analyze_progress_api_players__username__analyze_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Position
         * @description SSE live eval of one position: `eval` per depth, then `done`.
         */
        get: operations["eval_position_api_eval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain Move
         * @description SSE coach explanation of one played move; cached per (game, ply, agent).
         *
         *     `refresh=True` skips the cache read and regenerates, overwriting the
         *     cached row with the new result.
         */
        get: operations["explain_move_api_games__game_id__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coach Agents
         * @description The configured coach roster and the default agent id.
         */
        get: operations["coach_agents_api_coach_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Report
         * @description Aggregated stats over the player's analyzed games.
         *
         *     `since`/`until` (epoch seconds) restrict to a time window;
         *     `time_class` restricts to one time control.
         */
        get: operations["player_report_api_players__username__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/coach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Coach Player
         * @description Build the report, render the prompt, and ask the chosen agent.
         */
        post: operations["coach_player_api_players__username__coach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Game Ids */
            game_ids?: string[] | null;
            /** Limit */
            limit?: number | null;
        };
        /** AnalyzeResult */
        AnalyzeResult: {
            /** Queued */
            queued: number;
            /** Remaining */
            remaining: number;
        };
        /**
         * CoachAgentInfo
         * @description Selectable agent as shown to the UI; no LLM knobs exposed.
         */
        CoachAgentInfo: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "claude-agent-sdk" | "github-copilot" | "anthropic" | "azure-foundry";
            /** Model */
            model: string;
        };
        /** CoachAgentsResponse */
        CoachAgentsResponse: {
            /** Agents */
            agents: components["schemas"]["CoachAgentInfo"][];
            /** Default */
            default: string;
        };
        /** CoachRequest */
        CoachRequest: {
            /** Agent Id */
            agent_id?: string | null;
        };
        /** CoachResponse */
        CoachResponse: {
            /** Prompt */
            prompt: string;
            /** Advice */
            advice: string;
            /** Agent Id */
            agent_id: string;
        };
        /** CriticalPosition */
        CriticalPosition: {
            /** Fen */
            fen: string;
            /** Played */
            played: string;
            /** Best */
            best: string;
            /** Cp Loss */
            cp_loss: number;
            /** Game Id */
            game_id: string;
        };
        /** GameAnalysis */
        GameAnalysis: {
            /** Game Id */
            game_id: string;
            /** Depth */
            depth: number;
            /** Evals */
            evals: components["schemas"]["MoveEval"][];
            /** Overall Acpl */
            overall_acpl: number;
            /** Acpl By Phase */
            acpl_by_phase: {
                [key: string]: number;
            };
            /** Judgment Counts */
            judgment_counts: {
                [key: string]: number;
            };
        };
        /** GameDetail */
        GameDetail: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** Pgn */
            pgn: string;
            /** San Moves */
            san_moves: string[];
            /** Time Control */
            time_control: string;
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            /**
             * Result
             * @enum {string}
             */
            result: "win" | "loss" | "draw";
            /** End Time */
            end_time: number;
            /** Opponent */
            opponent: string;
            /** Player Rating */
            player_rating: number;
            /** Opponent Rating */
            opponent_rating: number;
            /** Accuracy */
            accuracy?: number | null;
            opening?: components["schemas"]["Opening"] | null;
            analysis?: components["schemas"]["GameAnalysis"] | null;
        };
        /** GameSummary */
        GameSummary: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** Pgn */
            pgn: string;
            /** San Moves */
            san_moves: string[];
            /** Time Control */
            time_control: string;
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            /**
             * Result
             * @enum {string}
             */
            result: "win" | "loss" | "draw";
            /** End Time */
            end_time: number;
            /** Opponent */
            opponent: string;
            /** Player Rating */
            player_rating: number;
            /** Opponent Rating */
            opponent_rating: number;
            /** Accuracy */
            accuracy?: number | null;
            opening?: components["schemas"]["Opening"] | null;
            /**
             * Analyzed
             * @default false
             */
            analyzed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MoveEval */
        MoveEval: {
            /** Ply */
            ply: number;
            /** San */
            san: string;
            /** Eval Cp */
            eval_cp: number | null;
            /** Eval Mate */
            eval_mate: number | null;
            /** Best Move */
            best_move: string;
            /** Cp Loss */
            cp_loss: number;
            /**
             * Judgment
             * @enum {string}
             */
            judgment: "best" | "good" | "inaccuracy" | "mistake" | "blunder";
        };
        /** Opening */
        Opening: {
            /** Eco */
            eco: string;
            /** Name */
            name: string;
            /** Ply */
            ply: number;
        };
        /** OpeningStats */
        OpeningStats: {
            /** Eco */
            eco: string;
            /** Name */
            name: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Draws */
            draws: number;
            /** Avg Cp Loss */
            avg_cp_loss?: number | null;
        };
        /** PlayerReport */
        PlayerReport: {
            /** Username */
            username: string;
            /** Games Analyzed */
            games_analyzed: number;
            /** Overall Acpl */
            overall_acpl: number;
            /** Acpl By Phase */
            acpl_by_phase: {
                [key: string]: number;
            };
            /** Judgment Counts */
            judgment_counts: {
                [key: string]: number;
            };
            /** Openings */
            openings: components["schemas"]["OpeningStats"][];
            /** Critical Positions */
            critical_positions: components["schemas"]["CriticalPosition"][];
        };
        /** SyncResult */
        SyncResult: {
            /** Games Synced */
            games_synced: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sync_player_api_players__username__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_openings_api_players__username__openings_get: {
        parameters: {
            query?: {
                since?: number | null;
                until?: number | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpeningStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_games_api_players__username__games_get: {
        parameters: {
            query?: {
                opening_eco?: string | null;
                result?: ("win" | "loss" | "draw") | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
                analyzed?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_detail_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_player_api_players__username__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_progress_api_players__username__analyze_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eval_position_api_eval_get: {
        parameters: {
            query: {
                fen: string;
                depth?: number | null;
                multipv?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_move_api_games__game_id__explain_get: {
        parameters: {
            query: {
                ply: number;
                agent_id?: string | null;
                refresh?: boolean;
            };
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coach_agents_api_coach_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachAgentsResponse"];
                };
            };
        };
    };
    player_report_api_players__username__report_get: {
        parameters: {
            query?: {
                since?: number | null;
                until?: number | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coach_player_api_players__username__coach_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CoachRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
