/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/players/{username}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Player
         * @description Fetch new games from chess.com, store and classify them.
         */
        post: operations["sync_player_api_players__username__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/openings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Openings
         * @description Per-opening record over classified games, most-played first.
         */
        get: operations["player_openings_api_players__username__openings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Games */
        get: operations["player_games_api_players__username__games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game Detail */
        get: operations["game_detail_api_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** GameAnalysis */
        GameAnalysis: {
            /** Game Id */
            game_id: string;
            /** Depth */
            depth: number;
            /** Evals */
            evals: components["schemas"]["MoveEval"][];
            /** Acpl By Phase */
            acpl_by_phase: {
                [key: string]: number;
            };
            /** Judgment Counts */
            judgment_counts: {
                [key: string]: number;
            };
        };
        /** GameDetail */
        GameDetail: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** Pgn */
            pgn: string;
            /** San Moves */
            san_moves: string[];
            /** Time Control */
            time_control: string;
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            /**
             * Result
             * @enum {string}
             */
            result: "win" | "loss" | "draw";
            /** End Time */
            end_time: number;
            /** Opponent */
            opponent: string;
            /** Player Rating */
            player_rating: number;
            /** Opponent Rating */
            opponent_rating: number;
            /** Accuracy */
            accuracy?: number | null;
            opening?: components["schemas"]["Opening"] | null;
            analysis?: components["schemas"]["GameAnalysis"] | null;
        };
        /** GameSummary */
        GameSummary: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** Pgn */
            pgn: string;
            /** San Moves */
            san_moves: string[];
            /** Time Control */
            time_control: string;
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            /**
             * Result
             * @enum {string}
             */
            result: "win" | "loss" | "draw";
            /** End Time */
            end_time: number;
            /** Opponent */
            opponent: string;
            /** Player Rating */
            player_rating: number;
            /** Opponent Rating */
            opponent_rating: number;
            /** Accuracy */
            accuracy?: number | null;
            opening?: components["schemas"]["Opening"] | null;
            /**
             * Analyzed
             * @default false
             */
            analyzed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MoveEval */
        MoveEval: {
            /** Ply */
            ply: number;
            /** San */
            san: string;
            /** Eval Cp */
            eval_cp: number | null;
            /** Eval Mate */
            eval_mate: number | null;
            /** Best Move */
            best_move: string;
            /** Cp Loss */
            cp_loss: number;
            /**
             * Judgment
             * @enum {string}
             */
            judgment: "best" | "good" | "inaccuracy" | "mistake" | "blunder";
        };
        /** Opening */
        Opening: {
            /** Eco */
            eco: string;
            /** Name */
            name: string;
            /** Ply */
            ply: number;
        };
        /** OpeningStats */
        OpeningStats: {
            /** Eco */
            eco: string;
            /** Name */
            name: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Draws */
            draws: number;
            /** Avg Cp Loss */
            avg_cp_loss?: number | null;
        };
        /** SyncResult */
        SyncResult: {
            /** Games Synced */
            games_synced: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sync_player_api_players__username__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_openings_api_players__username__openings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpeningStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_games_api_players__username__games_get: {
        parameters: {
            query?: {
                opening_eco?: string | null;
                result?: ("win" | "loss" | "draw") | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
                analyzed?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_detail_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
