/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/players/{username}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Player
         * @description Fetch new games from chess.com, store and classify them.
         *
         *     `full=True` re-fetches the entire archive instead of just the games
         *     since the last sync — the upsert makes this idempotent — to backfill
         *     columns added after games were stored (currently `termination`); a
         *     normal sync never re-fetches a stored game, so only a full re-sync
         *     can pick up such a column for existing rows.
         */
        post: operations["sync_player_api_players__username__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Players
         * @description Every stored player, most games first — the saved-players picker.
         */
        get: operations["list_all_players_api_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/openings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Openings
         * @description Per-opening record over classified games, most-played first.
         *
         *     `since`/`until` (epoch seconds) restrict to a time window;
         *     `time_class` restricts to one time control.
         */
        get: operations["player_openings_api_players__username__openings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/openings/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Openings Tree
         * @description Per-color repertoire move tree (docs/future-improvements/
         *     openings-explorer.md): drill from 1.e4 into any line, with games,
         *     score, eval, book status, and continuations at every node.
         *
         *     `since`/`until`/`time_class` scope the games exactly like
         *     `/openings`. `min_games` (default 2, clamped 1-10) prunes one-off
         *     deviations; `max_plies` (default 30, clamped 4-40) caps tree depth,
         *     mirroring `classify`'s book-ply cap. Both clamps are silent
         *     (max/min, no 422), like `/api/eval`'s depth/multipv. An unknown
         *     player has no stored games, so this returns an empty tree
         *     (`games=0`, a childless root) rather than 404ing, consistent with
         *     `/openings` and `/report`.
         */
        get: operations["player_openings_tree_api_players__username__openings_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Games */
        get: operations["player_games_api_players__username__games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game Detail */
        get: operations["game_detail_api_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Player
         * @description Queue engine analysis; follow progress via the SSE endpoint.
         */
        post: operations["analyze_player_api_players__username__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/analyze/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analyze Progress
         * @description SSE stream for the player's current analysis run.
         */
        get: operations["analyze_progress_api_players__username__analyze_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Position
         * @description SSE live eval of one position: `eval` per depth, then `done`.
         */
        get: operations["eval_position_api_eval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain Move
         * @description SSE coach explanation of one played move; cached per (game, ply, agent).
         *
         *     `refresh=True` skips the cache read and regenerates, overwriting the
         *     cached row with the new result.
         */
        get: operations["explain_move_api_games__game_id__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coach Agents
         * @description The configured coach roster and the default agent id.
         */
        get: operations["coach_agents_api_coach_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Report
         * @description Aggregated stats over the player's games.
         *
         *     `since`/`until` (epoch seconds) restrict to a time window;
         *     `time_class` restricts to one time control.
         *
         *     Both lists go in (docs/06-coach.md, "Volume and quality"): the
         *     analyzed games carry ACPL, judgments and error patterns, the full
         *     scope carries ratings, records and repertoire counts. `all_games`
         *     also *is* the scope count, so it replaces the separate
         *     `count_games` query rather than adding to it.
         */
        get: operations["player_report_api_players__username__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/highlights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Highlights
         * @description Blunders and brilliancies over the player's analyzed games.
         *
         *     `since`/`until` (epoch seconds) restrict to a time window;
         *     `time_class` restricts to one time control — same as `/report`. An
         *     unknown player simply has no analyzed games, so this returns empty
         *     lists rather than 404ing, consistent with `/report`/`/openings`.
         */
        get: operations["player_highlights_api_players__username__highlights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/coach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Coach Player
         * @description Build the report, render the prompt, and ask the chosen agent.
         *
         *     Coaching is the most expensive call the app makes, so — like
         *     `GET /games/{id}/explain` — it is cached: the window/time-class
         *     filters are part of the cache key alongside the agent and
         *     `coach.PROMPT_VERSION`, with a `refresh` escape hatch that skips the
         *     cache read and overwrites the cached row.
         */
        post: operations["coach_player_api_players__username__coach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Profile
         * @description The student profile (docs/06-coach.md, "Player profile"): facts are
         *     always freshly aggregated -- never an LLM call -- and the stored
         *     narrative, when one exists, is attached to the facts' `narrative`
         *     field alongside its own metadata.
         *
         *     Facts honour all three filters. The narrative is looked up by
         *     `time_class` alone, because that is the only dimension it is stored
         *     under: `since` moves with the calendar, so keying the narrative on it
         *     would strand every stored row overnight. A windowed request therefore
         *     returns windowed facts beside a narrative describing that control's
         *     whole history -- `narrative_games_now` states the latter's own live
         *     count so the UI can label both honestly.
         *
         *     An unknown player has no stored games, so this returns empty facts
         *     and no narrative, 200 like `/report`.
         */
        get: operations["player_profile_api_players__username__profile_get"];
        put?: never;
        /**
         * Regenerate Player Profile
         * @description Regenerate the narrative (user-triggered -- LLM calls cost money;
         *     GET never generates): fresh facts -> `render_profile_prompt` -> the
         *     chosen agent's `complete` with the read-only chat toolkit
         *     (docs/06-coach.md, "Narrative") -> `save_player_profile`. Responds
         *     with the same shape as `GET`. 409 when there are no analyzed games
         *     to describe.
         *
         *     Generated over the time control's **full** history, never a window:
         *     the narrative is the durable artifact other prompts embed, and one
         *     written over "the last 30 days" would be silently wrong the moment
         *     those 30 days moved. Time control is the one scope it carries.
         */
        post: operations["regenerate_player_profile_api_players__username__profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{username}/chat/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Chat Threads
         * @description The player's threads, most recently updated first.
         */
        get: operations["player_chat_threads_api_players__username__chat_threads_get"];
        put?: never;
        /**
         * Start Chat Thread
         * @description Create a chat thread anchored to a game (optionally a ply) or to
         *     the report window; mints a uuid4 thread id.
         *
         *     `scope="game"` requires `game_id` (400 without; 404 for an unknown
         *     game, or one belonging to another player); a `ply` anchor additionally
         *     requires analysis (409 unanalyzed, 400 out of range, mirroring
         *     `/explain`). `scope="report"` rejects `game_id`/`ply` (400). An
         *     unknown `agent_id` is 400; omitted means the configured default agent.
         */
        post: operations["start_chat_thread_api_players__username__chat_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat Thread Detail */
        get: operations["chat_thread_detail_api_chat_threads__thread_id__get"];
        put?: never;
        post?: never;
        /** Remove Chat Thread */
        delete: operations["remove_chat_thread_api_chat_threads__thread_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Chat Message
         * @description SSE reply to one chat message: `text`/`tool` events mirroring coach
         *     `ChatEvent` while the agent works, then `done` with the full reply —
         *     persisted (with the new `provider_state`) before `done` is emitted.
         *     `error` on a mid-stream `CoachProviderError`: nothing persisted,
         *     `provider_state` cleared. 404 unknown thread; 409 while a reply is
         *     already streaming for this thread, or the thread is at the message cap.
         */
        post: operations["send_chat_message_api_chat_threads__thread_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Game Ids */
            game_ids?: string[] | null;
            /** Limit */
            limit?: number | null;
            /** Since */
            since?: number | null;
            /** Until */
            until?: number | null;
            /** Time Class */
            time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
        };
        /** AnalyzeResult */
        AnalyzeResult: {
            /** Queued */
            queued: number;
            /** Remaining */
            remaining: number;
        };
        /**
         * BestWin
         * @description The strongest opponent the player beat in scope.
         *
         *     A milestone, not an aggregate: the one game a student actually
         *     remembers, and the only figure in a profile that says the ceiling
         *     is higher than the average. Volume-layer — beating a 1900 is a fact
         *     about the game, not about whether an engine has looked at it — so
         *     it is drawn from every stored game, analyzed or not.
         *
         *     Carries the game's identity for the same reason `CriticalPosition`
         *     does: the UI deep-links it (`/games/{id}`) and a coach can name the
         *     opponent and date rather than "one of your games".
         */
        BestWin: {
            /** Game Id */
            game_id: string;
            /** End Time */
            end_time: number;
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** Opponent */
            opponent: string;
            /** Opponent Rating */
            opponent_rating: number;
            /** Player Rating */
            player_rating: number;
        };
        /**
         * BookMove
         * @description One book continuation out of a position (docs/05-openings.md).
         *
         *     `eco`/`name` describe the position this move reaches, when that
         *     position is itself a named entry — `None` for an interior book
         *     position, in which case display inherits the caller's current
         *     name. `played` is filled in by the repertoire builder; a bare
         *     `OpeningBook.continuations()` call always returns `played=False`,
         *     since the book alone has no notion of which games were played.
         */
        BookMove: {
            /** San */
            san: string;
            /** Eco */
            eco: string | null;
            /** Name */
            name: string | null;
            /**
             * Played
             * @default false
             */
            played: boolean;
        };
        /**
         * ChatMessage
         * @description One chat turn — the unit both the transcript store and the
         *     provider replay path share.
         *
         *     Stored per thread by storage (docs/03-storage.md) and passed as
         *     `history` through the coach provider seam (docs/06-coach.md,
         *     `CoachProvider.chat`), which is what makes it a domain type. The
         *     stored transcript is the conversation's single source of truth;
         *     provider-side sessions are only ever a cache of it.
         */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Created At */
            created_at: number;
        };
        /** ChatMessageRequest */
        ChatMessageRequest: {
            /** Text */
            text: string;
        };
        /** ChatThread */
        ChatThread: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Agent Id */
            agent_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "report" | "game";
            /** Game Id */
            game_id?: string | null;
            /** Ply */
            ply?: number | null;
            /**
             * Since
             * @default 0
             */
            since: number;
            /**
             * Until
             * @default 0
             */
            until: number;
            /**
             * Time Class
             * @default
             */
            time_class: string;
            /** Provider State */
            provider_state?: string | null;
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
        };
        /** ChatThreadCreateRequest */
        ChatThreadCreateRequest: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "report" | "game";
            /** Agent Id */
            agent_id?: string | null;
            /** Game Id */
            game_id?: string | null;
            /** Ply */
            ply?: number | null;
            /** Since */
            since?: number | null;
            /** Until */
            until?: number | null;
            /** Time Class */
            time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
        };
        /**
         * ChatThreadDetail
         * @description Thread + full transcript, oldest first.
         */
        ChatThreadDetail: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Agent Id */
            agent_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "report" | "game";
            /** Game Id */
            game_id?: string | null;
            /** Ply */
            ply?: number | null;
            /**
             * Since
             * @default 0
             */
            since: number;
            /**
             * Until
             * @default 0
             */
            until: number;
            /**
             * Time Class
             * @default
             */
            time_class: string;
            /** Provider State */
            provider_state?: string | null;
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /**
         * ChatThreadSummary
         * @description One thread-list row.
         */
        ChatThreadSummary: {
            /** Id */
            id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "report" | "game";
            /** Game Id */
            game_id: string | null;
            /** Ply */
            ply: number | null;
            /** Since */
            since: number;
            /** Until */
            until: number;
            /** Time Class */
            time_class: string;
            /** Agent Id */
            agent_id: string;
            /** Title */
            title: string;
            /** Messages */
            messages: number;
            /** Updated At */
            updated_at: number;
        };
        /**
         * CoachAgentInfo
         * @description Selectable agent as shown to the UI; no LLM knobs exposed.
         */
        CoachAgentInfo: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "claude-agent-sdk" | "github-copilot";
            /** Model */
            model: string;
        };
        /** CoachAgentsResponse */
        CoachAgentsResponse: {
            /** Agents */
            agents: components["schemas"]["CoachAgentInfo"][];
            /** Default */
            default: string;
        };
        /** CoachRequest */
        CoachRequest: {
            /** Agent Id */
            agent_id?: string | null;
            /** Since */
            since?: number | null;
            /** Until */
            until?: number | null;
            /** Time Class */
            time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
            /**
             * Refresh
             * @default false
             */
            refresh: boolean;
        };
        /** CoachResponse */
        CoachResponse: {
            /** Prompt */
            prompt: string;
            /** Advice */
            advice: string;
            /** Agent Id */
            agent_id: string;
            /** Cached */
            cached: boolean;
            /** Generated At */
            generated_at: number;
            /** Games Analyzed */
            games_analyzed: number;
        };
        /**
         * Comparison
         * @description Two disjoint buckets of the same games, with a verdict
         *     (docs/06-coach.md, "Reading a comparison").
         *
         *     `significant` is decided over the profile's whole comparison family
         *     by Benjamini-Hochberg, never per row, which is the entire point: a
         *     profile makes up to fourteen of these, and judging each on its own
         *     manufactures roughly one spurious tendency every other student.
         */
        Comparison: {
            /** Label */
            label: string;
            /** Left Label */
            left_label: string;
            left: components["schemas"]["Record"];
            /** Right Label */
            right_label: string;
            right: components["schemas"]["Record"];
            /** Gap */
            gap: number;
            /**
             * Baseline
             * @default 0
             */
            baseline: number;
            /** Resolution */
            resolution: number;
            /** Significant */
            significant: boolean;
        };
        /**
         * CriticalPosition
         * @description A turning point the student can actually find and act on.
         *
         *     Identity (opponent, date, time class, color, opening, move number)
         *     so the prompt can say "in your game against marko77 on June 14,
         *     26...Nb6" instead of "position 1" — opponent and date because that
         *     is how players remember games — and the eval either side of the
         *     move so a blunder that lost a won game is distinguishable from one
         *     played in an already-lost position.
         */
        CriticalPosition: {
            /** Game Id */
            game_id: string;
            /** End Time */
            end_time: number;
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** Opponent */
            opponent: string;
            /** Opening Name */
            opening_name: string | null;
            /** Ply */
            ply: number;
            /** Move Number */
            move_number: number;
            /** Fen */
            fen: string;
            /** Leading Up */
            leading_up: string[];
            /** Played */
            played: string;
            /** Best */
            best: string;
            /** Cp Loss */
            cp_loss: number;
            /** Eval Before Cp */
            eval_before_cp: number | null;
            /** Eval Before Mate */
            eval_before_mate: number | null;
            /** Eval After Cp */
            eval_after_cp: number | null;
            /** Eval After Mate */
            eval_after_mate: number | null;
        };
        /**
         * Drawdown
         * @description The largest peak-to-trough fall in the archive, with its
         *     recovery (docs/06-coach.md, "Trajectory").
         *
         *     A window is a stationarity assumption and a drawdown is the
         *     opposite, so this is reported as its own fact rather than left for
         *     whichever window happens to contain it. `record` covers the fall
         *     itself; `since_record` covers everything after the trough, which is
         *     what makes "clawed back" or "still down there" sayable.
         */
        Drawdown: {
            /** Peak */
            peak: number;
            /** Peak At */
            peak_at: number;
            /** Trough */
            trough: number;
            /** Trough At */
            trough_at: number;
            record: components["schemas"]["Record"];
            since_record: components["schemas"]["Record"];
            /** Recovered */
            recovered: boolean;
        };
        /**
         * ErrorPattern
         * @description A recurring mistake, tagged deterministically with python-chess.
         *
         *     Counts generalize where anecdotes do not: "you hung a piece to a
         *     check 34 times" outweighs five sample positions and costs no LLM
         *     tokens. Tags are assigned by static analysis of the position, never
         *     by a model.
         */
        ErrorPattern: {
            /** Pattern */
            pattern: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
            /** Share Of Blunders */
            share_of_blunders: number;
            /** Example Game Id */
            example_game_id?: string | null;
            /** Example Ply */
            example_ply?: number | null;
            /** Example End Time */
            example_end_time?: number | null;
            /** Example Move Number */
            example_move_number?: number | null;
            /** Example Opponent */
            example_opponent?: string | null;
        };
        /** GameAnalysis */
        GameAnalysis: {
            /** Game Id */
            game_id: string;
            /** Depth */
            depth: number;
            /** Evals */
            evals: components["schemas"]["MoveEval"][];
            /** Overall Acpl */
            overall_acpl: number;
            /** Acpl By Phase */
            acpl_by_phase: {
                [key: string]: number;
            };
            /** Judgment Counts */
            judgment_counts: {
                [key: string]: number;
            };
        };
        /** GameDetail */
        GameDetail: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** Pgn */
            pgn: string;
            /** San Moves */
            san_moves: string[];
            /** Time Control */
            time_control: string;
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            /**
             * Result
             * @enum {string}
             */
            result: "win" | "loss" | "draw";
            /** End Time */
            end_time: number;
            /** Opponent */
            opponent: string;
            /** Player Rating */
            player_rating: number;
            /** Opponent Rating */
            opponent_rating: number;
            /** Accuracy */
            accuracy?: number | null;
            /** Termination */
            termination?: string | null;
            opening?: components["schemas"]["Opening"] | null;
            analysis?: components["schemas"]["GameAnalysis"] | null;
        };
        /**
         * GameSummary
         * @description One row of the games list — everything the list views render,
         *     nothing they don't.
         *
         *     Deliberately not a `Game`: the full record ships `pgn` (~2.3 KB a
         *     row) and every SAN move, which no list view renders, and at
         *     thousands of rows that weight is what forced the frontend to cap
         *     its fetch-everything helper — truncating the Dashboard's stats.
         *     `first_plies` is the first 6 SAN plies: the exact prefix the
         *     repertoire drill-through needs to derive the player's three-move
         *     system client-side. It is not the game record; that stays on
         *     `GameDetail`.
         */
        GameSummary: {
            /** Id */
            id: string;
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            /**
             * Result
             * @enum {string}
             */
            result: "win" | "loss" | "draw";
            /** End Time */
            end_time: number;
            /** Opponent */
            opponent: string;
            /** Player Rating */
            player_rating: number;
            /** Opponent Rating */
            opponent_rating: number;
            /** Accuracy */
            accuracy?: number | null;
            /** Termination */
            termination?: string | null;
            /** First Plies */
            first_plies: string[];
            opening?: components["schemas"]["Opening"] | null;
            /**
             * Analyzed
             * @default false
             */
            analyzed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HighlightMove
         * @description One linkable move for the Dashboard's blunders/brilliancies lists.
         */
        HighlightMove: {
            /** Game Id */
            game_id: string;
            /** End Time */
            end_time: number;
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /**
             * Result
             * @enum {string}
             */
            result: "win" | "loss" | "draw";
            /** Opponent */
            opponent: string;
            /** Opening Name */
            opening_name: string | null;
            /** Ply */
            ply: number;
            /** Move Number */
            move_number: number;
            /** San */
            san: string;
            /** Cp Loss */
            cp_loss: number;
            /** Eval After Cp */
            eval_after_cp: number | null;
            /** Eval After Mate */
            eval_after_mate: number | null;
        };
        /**
         * MonthStats
         * @description One calendar month — the trend row that says whether it helped.
         */
        MonthStats: {
            /** Month */
            month: string;
            /** Games */
            games: number;
            /** Rating End */
            rating_end: number | null;
            /** Rating Median */
            rating_median?: number | null;
            /** Acpl */
            acpl: number | null;
            /** Blunder Rate */
            blunder_rate: number | null;
        };
        /** MoveEval */
        MoveEval: {
            /** Ply */
            ply: number;
            /** San */
            san: string;
            /** Eval Cp */
            eval_cp: number | null;
            /** Eval Mate */
            eval_mate: number | null;
            /** Best Move */
            best_move: string;
            /** Cp Loss */
            cp_loss: number;
            /**
             * Judgment
             * @enum {string}
             */
            judgment: "best" | "good" | "inaccuracy" | "mistake" | "blunder";
        };
        /** Opening */
        Opening: {
            /** Eco */
            eco: string;
            /** Name */
            name: string;
            /** Ply */
            ply: number;
        };
        /**
         * OpeningStats
         * @description One opening as the player met it, from one side of the board.
         *
         *     Rows are keyed by (color, eco, name): an opening is a property of
         *     the *game*, so without `color` the table silently merges the lines
         *     the player chose with the ones their opponents chose against them.
         *
         *     The two move strings do the work no opening name can. `system` is
         *     the player's *own* first moves and nothing else — it is what a
         *     repertoire actually is, and grouping on it separates the openings
         *     they chose from the ones they merely faced. `first_moves` shows the
         *     same line with both sides answering, which is what makes a gambit
         *     visibly the opponent's. Consumers partition rows by `faced`, then
         *     roll the chosen partition up by (color, system) and the faced one
         *     by (color, name root); the rules are stated once in
         *     docs/06-coach.md and implemented against this type by both the
         *     report and the Dashboard.
         */
        OpeningStats: {
            /** Eco */
            eco: string;
            /** Name */
            name: string;
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** System */
            system: string;
            /** First Moves */
            first_moves: string;
            /** Faced */
            faced: boolean;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Draws */
            draws: number;
            /** Analyzed Games */
            analyzed_games: number;
            /** Opening Acpl */
            opening_acpl?: number | null;
            /** Avg Cp Loss */
            avg_cp_loss?: number | null;
            /**
             * Opening Moves
             * @default 0
             */
            opening_moves: number;
            /**
             * Player Moves
             * @default 0
             */
            player_moves: number;
        };
        /**
         * OpponentStats
         * @description How the player scores against stronger and weaker opposition.
         */
        OpponentStats: {
            /** Avg Rating Diff */
            avg_rating_diff: number;
            vs_stronger: components["schemas"]["Record"];
            vs_similar: components["schemas"]["Record"];
            vs_weaker: components["schemas"]["Record"];
        };
        /**
         * PeriodStats
         * @description Performance over one trailing window, so recent form outweighs
         *     ancient history.
         *
         *     The months table answers "what happened in March"; this answers
         *     "how is the student playing *now*", which is the question a profile
         *     exists to answer. Windows are cumulative and nested (last 30 days
         *     ⊂ last 90 ⊂ the whole covered span) rather than disjoint buckets:
         *     a month with four analyzed games produces an ACPL that swings on a
         *     single bad game, and a narrative reading that wobble as a trend is
         *     worse than one reading nothing. Nesting means a thin recent window
         *     is backed by a wider one that is still more recent than the span.
         *
         *     Carries both denominators for the same reason the report does:
         *     `games`/`record` are volume over every stored game in the window,
         *     `analyzed_games`/`player_moves` are the quality figures' own
         *     sample. A window can have games and no analysis at all, which is
         *     exactly when `acpl` must read as absent rather than as 0.0.
         */
        PeriodStats: {
            /** Label */
            label: string;
            /** Days */
            days: number | null;
            /** Games */
            games: number;
            record: components["schemas"]["Record"];
            /** Analyzed Games */
            analyzed_games: number;
            /** Player Moves */
            player_moves: number;
            /** Acpl */
            acpl: number | null;
            /** Blunder Rate */
            blunder_rate: number | null;
            /** Rating End */
            rating_end: number | null;
        };
        /**
         * PhaseStats
         * @description Player-move aggregates for one phase, with its denominator.
         *
         *     `acpl` is total centipawn loss ÷ `moves` — never a mean of per-game
         *     means — and is None when the player made no moves in the phase. A
         *     phase the games never reached must read as "no moves", not as 0.0
         *     centipawn loss, which is indistinguishable from flawless play.
         */
        PhaseStats: {
            /** Moves */
            moves: number;
            /** Acpl */
            acpl: number | null;
            /** Judgment Counts */
            judgment_counts: {
                [key: string]: number;
            };
        };
        /** PlayerHighlights */
        PlayerHighlights: {
            /** Blunders */
            blunders: components["schemas"]["HighlightMove"][];
            /** Brilliancies */
            brilliancies: components["schemas"]["HighlightMove"][];
        };
        /**
         * PlayerProfile
         * @description The durable who-is-this-student artifact (docs/06-coach.md).
         *
         *     Two layers. Deterministic facts, distilled from a `PlayerReport` by
         *     `build_profile` — free, recomputed on demand. And an LLM
         *     `narrative`, generated only on explicit user action and cached by
         *     storage (docs/03-storage.md, `player_profiles`), where the facts
         *     persist beside it as the snapshot the narrative described. Kept
         *     compact on purpose: `render_profile_context` turns it into the
         *     ~250-token block other coach prompts embed at the top, so every
         *     list here is capped by the builder.
         *
         *     Inherits `PlayerReport`'s volume/quality split and both of its
         *     denominators — see that docstring. `games_covered` is the analyzed
         *     sample behind the quality figures; `games_in_scope` is every stored
         *     game behind the ratings, records and repertoire counts.
         */
        PlayerProfile: {
            /** Username */
            username: string;
            /** Time Class */
            time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
            /** Games Covered */
            games_covered: number;
            /**
             * Games In Scope
             * @default 0
             */
            games_in_scope: number;
            /** Window Start */
            window_start: number | null;
            /** Window End */
            window_end: number | null;
            /** Player Moves */
            player_moves: number;
            /** Overall Acpl */
            overall_acpl: number;
            /** Judgment Counts */
            judgment_counts: {
                [key: string]: number;
            };
            /** Phases */
            phases: {
                [key: string]: components["schemas"]["PhaseStats"];
            };
            /** Time Classes */
            time_classes: components["schemas"]["TimeClassStats"][];
            /** Months */
            months: components["schemas"]["MonthStats"][];
            /**
             * Periods
             * @default []
             */
            periods: components["schemas"]["PeriodStats"][];
            /**
             * @default {
             *       "games": 0,
             *       "wins": 0,
             *       "losses": 0,
             *       "draws": 0
             *     }
             */
            record: components["schemas"]["Record"];
            /**
             * Color Records
             * @default {}
             */
            color_records: {
                [key: string]: components["schemas"]["Record"];
            };
            best_win?: components["schemas"]["BestWin"] | null;
            streaks?: components["schemas"]["StreakStats"] | null;
            opponents?: components["schemas"]["OpponentStats"] | null;
            /**
             * Terminations
             * @default []
             */
            terminations: components["schemas"]["TerminationStats"][];
            /** Openings */
            openings: components["schemas"]["ProfileOpening"][];
            /** Error Patterns */
            error_patterns: components["schemas"]["ErrorPattern"][];
            /** Analyzed Window Start */
            analyzed_window_start?: number | null;
            /** Analyzed Window End */
            analyzed_window_end?: number | null;
            trajectory?: components["schemas"]["RatingTrajectory"] | null;
            /**
             * Window Spans Level Change
             * @default false
             */
            window_spans_level_change: boolean;
            /**
             * Comparisons
             * @default []
             */
            comparisons: components["schemas"]["Comparison"][];
            /** Narrative */
            narrative?: string | null;
        };
        /**
         * PlayerReport
         * @description Everything the coaching prompt and the Dashboard read.
         *
         *     Two layers with two different denominators (docs/06-coach.md,
         *     "Volume and quality"). **Volume** — `record`, `time_classes` and
         *     their ratings, `months` game counts, `terminations`, `opponents`,
         *     `color_records`, `best_win`, `streaks`, and the repertoire's
         *     `games`/win-loss columns — describes every
         *     stored game in scope. **Quality** — `overall_acpl`,
         *     `judgment_counts`, `phases`, `error_patterns`, `critical_positions`,
         *     the ACPL columns, and `months` ACPL/blunder rate — describes the
         *     analyzed subset, because nothing else can produce it.
         *
         *     Mixing the two is what made a partly-analyzed archive report a
         *     rating from whichever game happened to be analyzed last, months
         *     after the fact. `games_analyzed` and `games_in_scope` are the two
         *     denominators, stated rather than implied.
         *
         *     `window_start`/`window_end` report the extent of the data actually
         *     covered, so neither the model nor the student has to guess what
         *     period the numbers describe.
         */
        PlayerReport: {
            /** Username */
            username: string;
            /** Games Analyzed */
            games_analyzed: number;
            /** Player Moves */
            player_moves: number;
            /** Window Start */
            window_start: number | null;
            /** Window End */
            window_end: number | null;
            /** Analyzed Window Start */
            analyzed_window_start?: number | null;
            /** Analyzed Window End */
            analyzed_window_end?: number | null;
            /** Time Class */
            time_class: ("bullet" | "blitz" | "rapid" | "daily") | null;
            /** Requested Since */
            requested_since?: number | null;
            /** Requested Until */
            requested_until?: number | null;
            /** Games In Scope */
            games_in_scope?: number | null;
            record: components["schemas"]["Record"];
            /** Overall Acpl */
            overall_acpl: number;
            /** Phases */
            phases: {
                [key: string]: components["schemas"]["PhaseStats"];
            };
            /** Judgment Counts */
            judgment_counts: {
                [key: string]: number;
            };
            /** Time Classes */
            time_classes: components["schemas"]["TimeClassStats"][];
            /** Months */
            months: components["schemas"]["MonthStats"][];
            /**
             * Periods
             * @default []
             */
            periods: components["schemas"]["PeriodStats"][];
            /** Terminations */
            terminations: components["schemas"]["TerminationStats"][];
            opponents: components["schemas"]["OpponentStats"] | null;
            /**
             * Color Records
             * @default {}
             */
            color_records: {
                [key: string]: components["schemas"]["Record"];
            };
            best_win?: components["schemas"]["BestWin"] | null;
            streaks?: components["schemas"]["StreakStats"] | null;
            /** Openings */
            openings: components["schemas"]["OpeningStats"][];
            /** Error Patterns */
            error_patterns: components["schemas"]["ErrorPattern"][];
            /** Critical Positions */
            critical_positions: components["schemas"]["CriticalPosition"][];
        };
        /**
         * PlayerSummary
         * @description A stored player, for the saved-players picker.
         */
        PlayerSummary: {
            /** Username */
            username: string;
            /** Games */
            games: number;
            /** Last Played */
            last_played: number;
        };
        /** ProfileGenerateRequest */
        ProfileGenerateRequest: {
            /** Agent Id */
            agent_id?: string | null;
            /** Time Class */
            time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
        };
        /**
         * ProfileNarrative
         * @description Metadata for the profile's stored narrative: who generated it,
         *     under which prompt version, when, and how many games the *snapshot it
         *     described* covered. That last figure is deliberately the stored
         *     snapshot's `games_covered`, not the response's (always fresh)
         *     `profile.games_covered` -- together they let the UI say "narrative
         *     generated over N games; you have M now".
         */
        ProfileNarrative: {
            /** Agent Id */
            agent_id: string;
            /** Prompt Version */
            prompt_version: string;
            /** Generated At */
            generated_at: number;
            /** Games Covered */
            games_covered: number;
        };
        /**
         * ProfileOpening
         * @description One repertoire family in the player profile.
         *
         *     A row of the profile's compact repertoire: a family the player
         *     chooses (`faced=False`, `moves` is their own system) or a line they
         *     keep facing (`faced=True`, `moves` is the full line with both sides
         *     answering). Rolled up from `OpeningStats` under the family rules
         *     stated once in docs/06-coach.md — the profile restates the
         *     repertoire, it never re-derives its semantics.
         */
        ProfileOpening: {
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** Name */
            name: string;
            /** Moves */
            moves: string;
            /** Games */
            games: number;
            /** Score */
            score: number;
            /** Faced */
            faced: boolean;
            /** Opening Acpl */
            opening_acpl?: number | null;
            /** Avg Cp Loss */
            avg_cp_loss?: number | null;
        };
        /** ProfileResponse */
        ProfileResponse: {
            profile: components["schemas"]["PlayerProfile"];
            narrative?: components["schemas"]["ProfileNarrative"] | null;
            /** Narrative Games Now */
            narrative_games_now?: number | null;
            /**
             * Prompt Version
             * @default profile-v10
             */
            prompt_version: string;
        };
        /**
         * RatingDelta
         * @description Rating movement over one trailing span (docs/06-coach.md,
         *     "Trajectory").
         *
         *     `games` rides along because a delta over three games and a delta
         *     over three hundred are different claims, and the renderers say so.
         */
        RatingDelta: {
            /** Days */
            days: number;
            /** Rating Then */
            rating_then: number;
            /** Delta */
            delta: number;
            /** Games */
            games: number;
        };
        /**
         * RatingTrajectory
         * @description Where the student is heading, over the **full** archive
         *     (docs/06-coach.md, "Trajectory") — never the profile window, whose
         *     whole job is to hold the level roughly constant.
         *
         *     A coach's first question is the direction, and averages cannot
         *     answer it: on a student who has gone 185 to 1479 the archive mean
         *     describes nobody, while "up 443 points in a year" describes them
         *     exactly.
         */
        RatingTrajectory: {
            /** Rating Now */
            rating_now: number;
            /**
             * Deltas
             * @default []
             */
            deltas: components["schemas"]["RatingDelta"][];
            /** Rating Max */
            rating_max: number;
            /** Rating Max At */
            rating_max_at: number;
            /** Rating Min */
            rating_min: number;
            /** Rating Min At */
            rating_min_at: number;
            /** Games */
            games: number;
            /** Window Start */
            window_start?: number | null;
            /** Window End */
            window_end?: number | null;
            drawdown?: components["schemas"]["Drawdown"] | null;
        };
        /**
         * Record
         * @description A win/loss/draw tally. Score is (wins + draws/2) / games.
         */
        Record: {
            /**
             * Games
             * @default 0
             */
            games: number;
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Draws
             * @default 0
             */
            draws: number;
        };
        /** RepertoireNode */
        RepertoireNode: {
            /** San */
            san: string;
            /** Ply */
            ply: number;
            record: components["schemas"]["Record"];
            /** Analyzed */
            analyzed: number;
            /** Eco */
            eco: string | null;
            /** Name */
            name: string | null;
            /** In Book */
            in_book: boolean;
            /** Avg Eval Cp */
            avg_eval_cp: number | null;
            /** Avg Cp Loss */
            avg_cp_loss: number | null;
            /** Exits */
            exits: number;
            /** Book Moves */
            book_moves: components["schemas"]["BookMove"][];
            /** Children */
            children: components["schemas"]["RepertoireNode"][];
        };
        /** RepertoireTree */
        RepertoireTree: {
            /** Username */
            username: string;
            /**
             * Color
             * @enum {string}
             */
            color: "white" | "black";
            /** Games */
            games: number;
            /** Analyzed */
            analyzed: number;
            root: components["schemas"]["RepertoireNode"];
        };
        /**
         * StreakStats
         * @description Runs and rebounds — what the volume layer knows about momentum.
         *
         *     Two questions no lifetime average answers. **Are they on a run
         *     right now**: `current_*` describe the run the most recent game in
         *     scope belongs to, where a run is consecutive games with the same
         *     result (a draw is a run of draws, not a break in one), and
         *     `longest_*` are the longest such runs anywhere in scope. **Do they
         *     tilt**: `after_loss` is the record over games played in the same
         *     sitting as, and immediately after, a loss — set against the
         *     player's overall record it is the difference between "lost six
         *     today" and "lost one, then lost five chasing it".
         *
         *     `after_loss` is a strict subset of `record`, and its own `games`
         *     is the denominator: on a correspondence archive, or one with no
         *     back-to-back games at all, it is legitimately empty and must read
         *     as "no sample", never as a 0% score.
         */
        StreakStats: {
            /**
             * Current Result
             * @enum {string}
             */
            current_result: "win" | "loss" | "draw";
            /** Current Length */
            current_length: number;
            /** Longest Win */
            longest_win: number;
            /** Longest Loss */
            longest_loss: number;
            after_loss: components["schemas"]["Record"];
        };
        /** SyncResult */
        SyncResult: {
            /** Games Synced */
            games_synced: number;
        };
        /**
         * TerminationStats
         * @description How games ended — 'lost on time' and 'resigned' are not the same.
         */
        TerminationStats: {
            /**
             * Result
             * @enum {string}
             */
            result: "win" | "loss" | "draw";
            /** Termination */
            termination: string;
            /** Games */
            games: number;
        };
        /**
         * TimeClassStats
         * @description Play and rating movement within one time control.
         *
         *     The extremes carry their dates: "peaked at 1723" is trivia,
         *     "peaked at 1723 last March and has been below it since" is the
         *     fact a student measures themselves against. Both are the extreme
         *     *of the games in scope* — the archive stored here, not chess.com's
         *     own all-time best — and both are stamped at the **first** game that
         *     reached the value, since a peak is when they got there.
         */
        TimeClassStats: {
            /**
             * Time Class
             * @enum {string}
             */
            time_class: "bullet" | "blitz" | "rapid" | "daily";
            record: components["schemas"]["Record"];
            /** Rating Start */
            rating_start: number;
            /** Rating End */
            rating_end: number;
            /** Rating Min */
            rating_min: number;
            /** Rating Max */
            rating_max: number;
            /** Rating Max At */
            rating_max_at?: number | null;
            /** Rating Min At */
            rating_min_at?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sync_player_api_players__username__sync_post: {
        parameters: {
            query?: {
                full?: boolean;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_players_api_players_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSummary"][];
                };
            };
        };
    };
    player_openings_api_players__username__openings_get: {
        parameters: {
            query?: {
                since?: number | null;
                until?: number | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpeningStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_openings_tree_api_players__username__openings_tree_get: {
        parameters: {
            query: {
                color: "white" | "black";
                since?: number | null;
                until?: number | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
                min_games?: number;
                max_plies?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepertoireTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_games_api_players__username__games_get: {
        parameters: {
            query?: {
                opening_eco?: string | null;
                result?: ("win" | "loss" | "draw") | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
                analyzed?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_detail_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_player_api_players__username__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_progress_api_players__username__analyze_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eval_position_api_eval_get: {
        parameters: {
            query: {
                fen: string;
                depth?: number | null;
                multipv?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_move_api_games__game_id__explain_get: {
        parameters: {
            query: {
                ply: number;
                agent_id?: string | null;
                refresh?: boolean;
            };
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coach_agents_api_coach_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachAgentsResponse"];
                };
            };
        };
    };
    player_report_api_players__username__report_get: {
        parameters: {
            query?: {
                since?: number | null;
                until?: number | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_highlights_api_players__username__highlights_get: {
        parameters: {
            query?: {
                since?: number | null;
                until?: number | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerHighlights"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coach_player_api_players__username__coach_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CoachRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_profile_api_players__username__profile_get: {
        parameters: {
            query?: {
                since?: number | null;
                until?: number | null;
                time_class?: ("bullet" | "blitz" | "rapid" | "daily") | null;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_player_profile_api_players__username__profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProfileGenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_chat_threads_api_players__username__chat_threads_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_chat_thread_api_players__username__chat_threads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatThreadCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThread"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_thread_detail_api_chat_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_chat_thread_api_chat_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_chat_message_api_chat_threads__thread_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
